version: "3.1"
services:

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:80
    depends_on:
      - database
